version: "3"

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SERVER_PORT=50051
    volumes:
      - ./:/app
    command: sh -c "cd /app && go run server/main.go"
    deploy:
      restart_policy:
        condition: on-failure

  proxy:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./:/app
    command: sh -c "cd /app && go run client/main.go -proxy-port 50050 -server-addr server:50051"
    ports:
      - "50050:50050"
    depends_on:
      - server
