version: "3"
tasks:
  gen:
    desc: "Generate Go code from proto files using Docker"
    cmds:
      - |
        docker run --rm -v $(pwd):/workspace -w /workspace \
          golang:1.22-alpine sh -c '
            apk add --no-cache protobuf && \
            go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest && \
            export PATH=$PATH:/go/bin && \
            protoc --go_out=. --go_opt=paths=source_relative \
                   --go-grpc_out=. --go-grpc_opt=paths=source_relative \
                   proto/*.proto
          '

  server:
    desc: "Start server instances"
    cmds:
      - docker-compose up --scale server=3 -d server

  client:
    desc: "Start proxy server"
    cmds:
      - docker-compose up -d proxy

  up:
    desc: "Start all services (server and proxy)"
    cmds:
      - task: server
      - task: client

  down:
    desc: "Stop all services"
    cmds:
      - docker-compose down
